import { BUILDINGS } from "../data/buildings";
import { formatMinutes, parseDays } from "../utils/formatting";

function fillRate(section) {
  return section.enrolled / section.seats;
}

function pad(value) {
  return String(value).padStart(2, "0");
}

function formatIcsDate(date) {
  return `${date.getUTCFullYear()}${pad(date.getUTCMonth() + 1)}${pad(date.getUTCDate())}T${pad(date.getUTCHours())}${pad(date.getUTCMinutes())}00Z`;
}

function getNextDayIndex(dayCode) {
  const map = { M: 1, T: 2, W: 3, TH: 4, F: 5 };
  return map[dayCode];
}

function nextOccurrenceForDay(dayCode, time) {
  const now = new Date();
  const target = new Date(now);
  const dayIndex = getNextDayIndex(dayCode);
  const [hours, minutes] = time.split(":").map(Number);
  const currentDay = now.getDay();
  const normalizedCurrent = currentDay === 0 ? 7 : currentDay;
  let diff = dayIndex - normalizedCurrent;

  if (diff < 0 || (diff === 0 && (hours < now.getHours() || (hours === now.getHours() && minutes <= now.getMinutes())))) {
    diff += 7;
  }

  target.setDate(now.getDate() + diff);
  target.setHours(hours, minutes, 0, 0);
  return target;
}

function buildByDay(days) {
  const mapping = { M: "MO", T: "TU", W: "WE", TH: "TH", F: "FR" };
  return parseDays(days).map((day) => mapping[day]).join(",");
}

function buildUntilDate() {
  const until = new Date();
  until.setMonth(until.getMonth() + 4);
  until.setHours(23, 59, 0, 0);
  return until;
}

function escapeText(value) {
  return String(value)
    .replace(/\\/g, "\\\\")
    .replace(/;/g, "\\;")
    .replace(/,/g, "\\,")
    .replace(/\n/g, "\\n");
}

function sectionToIcsEvent(schedule, section) {
  const firstDay = parseDays(section.days)[0];
  const startDate = nextOccurrenceForDay(firstDay, section.start);
  const endDate = nextOccurrenceForDay(firstDay, section.end);
  const building = BUILDINGS[section.building];
  const location = building ? `${building.name} (${section.building}) ${section.room}` : `${section.building} ${section.room}`;
  const description = [
    `${section.courseId} - ${section.title}`,
    `Instructor: ${section.instructor}`,
    `Unique: ${section.unique}`,
    `Days: ${section.days}`,
    `Time: ${formatMinutes(startDate.getHours() * 60 + startDate.getMinutes())} - ${formatMinutes(endDate.getHours() * 60 + endDate.getMinutes())}`,
    `Generated by RateMySchedule schedule export`
  ].join("\n");

  return [
    "BEGIN:VEVENT",
    `UID:${section.unique}-${schedule.id}@ratemyschedule.local`,
    `DTSTAMP:${formatIcsDate(new Date())}`,
    `DTSTART:${formatIcsDate(startDate)}`,
    `DTEND:${formatIcsDate(endDate)}`,
    `RRULE:FREQ=WEEKLY;BYDAY=${buildByDay(section.days)};UNTIL=${formatIcsDate(buildUntilDate())}`,
    `SUMMARY:${escapeText(section.courseId)} ${escapeText(section.title)}`,
    `LOCATION:${escapeText(location)}`,
    `DESCRIPTION:${escapeText(description)}`,
    "END:VEVENT"
  ].join("\r\n");
}

function buildIcsFile(schedule) {
  return [
    "BEGIN:VCALENDAR",
    "VERSION:2.0",
    "PRODID:-//RateMySchedule//UT Austin Planner//EN",
    "CALSCALE:GREGORIAN",
    "METHOD:PUBLISH",
    ...schedule.sections.map((section) => sectionToIcsEvent(schedule, section)),
    "END:VCALENDAR"
  ].join("\r\n");
}

function downloadIcsFile(filename, content) {
  const blob = new Blob([content], { type: "text/calendar;charset=utf-8" });
  const url = URL.createObjectURL(blob);
  const anchor = document.createElement("a");
  anchor.href = url;
  anchor.download = filename;
  document.body.appendChild(anchor);
  anchor.click();
  anchor.remove();
  window.setTimeout(() => URL.revokeObjectURL(url), 1000);
}

export function buildRegistrationSheet(schedule) {
  return [...schedule.sections]
    .sort((left, right) => fillRate(right) - fillRate(left))
    .map((section, index) => ({
      order: index + 1,
      unique: section.unique,
      courseId: section.courseId,
      fillPercent: Math.round(fillRate(section) * 100),
      note: fillRate(section) >= 0.95 ? "enter first" : fillRate(section) >= 0.85 ? "high demand" : "safer pick"
    }));
}

export async function exportScheduleToCalendar(schedule) {
  await new Promise((resolve) => setTimeout(resolve, 900));

  const filename = `${schedule.nickname.toLowerCase().replace(/[^a-z0-9]+/g, "-")}.ics`;
  const icsContent = buildIcsFile(schedule);
  downloadIcsFile(filename, icsContent);

  return {
    success: true,
    eventCount: schedule.sections.length,
    deepLink: "https://calendar.google.com/calendar/u/0/r/settings/export",
    filename,
    message: `Downloaded ${filename} with recurring class events for ${schedule.nickname}. Import it into Google Calendar or drag it directly onto your calendar page.`,
    preview: schedule.sections.map((section) => `${section.courseId} · ${section.days} · ${section.start}-${section.end}`).join(" | ")
  };
}